/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.whatsapp.components;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Owner
 */
public class PanelPopupMessage extends javax.swing.JPanel {
    public static enum MessageType {
        SUCCESS, ERROR, LOGIN, LOGOUT
    }
    
    private boolean show;
    private MessageType messageType;
    
    public PanelPopupMessage() {
        initComponents();
        setOpaque(false);
        setVisible(false);
    }
    
    public void setShow(boolean show) {
        this.show = show;
    }
    
    public boolean getShow() {
        return show;
    }
    
    public void showMessage(MessageType messageType, String message) {
        this.setVisible(true);
        this.messageType = messageType;
        lblMessage.setText(message);
        if (messageType == MessageType.SUCCESS) {
            lblMessage.setBackground(new Color(38, 211, 124, 150));
            lblMessage.setIcon(new ImageIcon(getClass().getResource("/com/whatsapp/icons/success.png")));
        } else if(messageType == MessageType.ERROR){
            lblMessage.setBackground(new Color(240, 52, 53, 150));
            lblMessage.setIcon(new ImageIcon(getClass().getResource("/com/whatsapp/icons/error.png")));
        } else {
            lblMessage.setBackground(new Color(38, 211, 124, 150));
            lblMessage.setIcon(new ImageIcon(getClass().getResource("/com/whatsapp/icons/success.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();

        lblMessage.setBackground(new java.awt.Color(15, 174, 37));
        lblMessage.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("jLabel1");
        lblMessage.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
