/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.whatsapp.components;

import com.whatsapp.main.UserInformation;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Owner
 */
public class PanelHeader extends javax.swing.JPanel {

    private final MigLayout layout;
    private JLabel lblUser;
    
    
    public PanelHeader() {
        initComponents();
        setOpaque(false);
        layout = new MigLayout("fill, align right", "[right]");
        init();
    }
    
    private void init() {
        setLayout(layout);
        
        lblUser = new JLabel(PanelLoginAndRegister.superUsername);
        lblUser.setIcon(new ImageIcon(getClass().getResource("/com/whatsapp/icons/user.png")));
        lblUser.setFont(new Font("san serif",1, 16));
        lblUser.setForeground(Color.WHITE);
        lblUser.setOpaque(false);
        lblUser.setIconTextGap(10);
        lblUser.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                lblUserOnClick();
            }
        });
       this.add(lblUser, "align right");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        GradientPaint gra = new GradientPaint(0, 0, new Color(38, 211, 124), 0, getHeight(), new Color(22, 116, 66));
        g2.setPaint(gra);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(grphcs); 
    }
    
     private void lblUserOnClick() {
        new UserInformation(PanelLoginAndRegister.superUsername).setVisible(true);
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
