/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.whatsapp.components;

import com.whatsapp.swing.MyMessagePane;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Owner
 */
public class PanelMessageBubble extends javax.swing.JPanel {

    private final MigLayout layout;
    private JLabel lblTimestamp;
    private MyMessagePane pnMessage;
    
    public PanelMessageBubble(String message, String time, boolean isUser) {
        layout = new MigLayout("wrap 1", "[grow]", "[top][bottom]");
        initComponents();
        init(message, time, isUser);
    }
    
    private void init(String message, String time, boolean isUser) {
        this.setLayout(layout);
        
        pnMessage = new MyMessagePane();
        pnMessage.setText(message);
        pnMessage.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // Font as before
        pnMessage.setEditable(false);
        
        lblTimestamp = new JLabel(time);
        lblTimestamp.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        lblTimestamp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        
        if(isUser) {
            this.setBackground(new java.awt.Color(38, 211, 124));
        } else {
            this.setBackground(new java.awt.Color(230, 245, 241));
        }
        
        this.add(pnMessage, "align left"); 
        this.add(lblTimestamp, "align right, gapleft 10"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
//    @Override
//    public Dimension getPreferredSize() {
//        FontMetrics metrics = lblMessage.getFontMetrics(lblMessage.getFont());
//        int width;
//        int height = 50; 
//        if(lblMessage.getText().length() <= 2) 
//            width = 50;
//        else
//            width = metrics.stringWidth(lblMessage.getText()) + 30; // 30 for padding
//        
//        return new Dimension(width, height);
//    }
//
//    @Override
//    public Dimension getMaximumSize() {
//        return getPreferredSize(); // Ensure width doesn't exceed preferred size cause box layout tends to 
//                                   // expand components to full width of the parent container
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
