/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.whatsapp.components;

import com.whatsapp.swing.ButtonOutLine;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Owner
 */
public class PanelCover extends javax.swing.JPanel {

    private ActionListener event;
    private MigLayout layout;
    private JLabel lblTitle;
    private JLabel lblDescription1;
    private JLabel lblDescription2;
    private ButtonOutLine button;
    
    private boolean isLogin;
    private final DecimalFormat df = new DecimalFormat("##0.###", DecimalFormatSymbols.getInstance(Locale.US));
    
    
    public PanelCover() {
        initComponents();
        setOpaque(false);
        layout = new MigLayout("wrap, fill", "[center]", "push[]30[]10[]30[]push");
        setLayout(layout);
        init();
    }
    
    private void init() {
        lblTitle = new JLabel("Welcome Back!");
        lblTitle.setFont(new Font("sansserif", 1, 30));
        lblTitle.setForeground(new Color(245, 245, 245));
        add(lblTitle);
        lblDescription1 = new JLabel("To keep connected with your people");
        lblDescription1.setForeground(new Color(245, 245, 245));
        add(lblDescription1);
        lblDescription2 = new JLabel("login with your account credentials");
        lblDescription2.setForeground(new Color(245, 245, 245));
        add(lblDescription2);
        
        button = new ButtonOutLine();
        button.setBackground(new Color(255, 255, 255));
        button.setForeground(new Color(255, 255, 255));
        button.setText("SIGN IN");
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.actionPerformed(ae);   // this triggers the same actionPerformed() method which is in Main.java
            }
        });
        add(button, "w 60%, h 40");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        GradientPaint gra = new GradientPaint(0, 0, new Color(38, 211, 124), 0, getHeight(), new Color(22, 116, 66));
        g2.setPaint(gra);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(grphcs); 
    }

    public void addEvent(ActionListener event) {
        this.event = event;
    }
    
     public void registerLeft(double v) {
        v = Double.parseDouble(df.format(v));
        login(false);
        layout.setComponentConstraints(lblTitle, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(lblDescription1, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(lblDescription2, "pad 0 -" + v + "% 0 0");
    }

    public void registerRight(double v) {
        v = Double.parseDouble(df.format(v));
        login(false);
        layout.setComponentConstraints(lblTitle, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(lblDescription1, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(lblDescription2, "pad 0 -" + v + "% 0 0");
    }

    public void loginLeft(double v) {
        v = Double.parseDouble(df.format(v));
        login(true);
        layout.setComponentConstraints(lblTitle, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(lblDescription1, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(lblDescription2, "pad 0 " + v + "% 0 " + v + "%");
    }

    public void loginRight(double v) {
        v = Double.parseDouble(df.format(v));
        login(true);
        layout.setComponentConstraints(lblTitle, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(lblDescription1, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(lblDescription2, "pad 0 " + v + "% 0 " + v + "%");
    }

    public void login(boolean login) {
        if (this.isLogin != login) {
            if (login) {
                lblTitle.setText("Hello, Friend!");
                lblDescription1.setText("Don't have an account yet?");
                lblDescription2.setText("Sign up right here");
                button.setText("SIGN UP");
            } else {
                lblTitle.setText("Welcome Back!");
                lblDescription1.setText("To keep connected with us please");
                lblDescription2.setText("login with your account credentials");
                button.setText("SIGN IN");
            }
            this.isLogin = login;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
